<div class="Sirv" data-options="zoom.mode:magnifier; zoom.trigger:click; zoom.width:auto; zoom.hint.text.click:Click to zoom; zoom.map.enable:false; fullscreen.always:true; quality:100; hdQuality:100; contextmenu.enable:true">
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai/Hyundai.spin"></div>
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai-Decklid/Hyundai-Decklid.spin"></div>
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai-Door/Hyundai-Door.spin"></div>
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai-RT-Qtr/Hyundai-RT-Qtr.spin"></div>
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai-Fender/Hyundai-Fender.spin"></div>
  <div data-src="https://crashchampions.sirv.com/Spins/Hyundai-Quarter/Hyundai-Quarter.spin"></div>
</div> 
<script src="https://scripts.sirv.com/sirvjs/v3/sirv.js"></script>
